# Generated by Django 4.2.7 on 2023-11-22 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_remove_movie_ratings'),
        ('rating', '0002_rating_rating_rate_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.movie'),
            preserve_default=False,
        ),
    ]
