# Generated by Django 4.2.7 on 2023-11-22 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_rating_movie'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_rate_uniqueness',
        ),
    ]
