# Generated by Django 4.2.7 on 2023-11-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('storyline', models.CharField(max_length=255, verbose_name='Línea de historia')),
                ('content_rating', models.CharField(max_length=255, verbose_name='Rating de contenido')),
                ('duration', models.CharField(max_length=255, verbose_name='Duración')),
                ('release_date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('poster_image', models.CharField(max_length=255, verbose_name='Imagen de poster')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('viewer_count', models.IntegerField(verbose_name='Contador de visitas')),
                ('ratings', models.ManyToManyField(to='rating.rating', verbose_name='Calificaciones')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'db_table': 'movie',
                'indexes': [models.Index(fields=['title'], name='movie_title_idx')],
            },
        ),
    ]
